development:
    PARSE_APP_ID: DoZASTALoss5wZIOd8SAJQSSjki4BBrQ2QyHClVr
    PARSE_REST_KEY:  7hWoKQa689ObInDuZq0x0S3J1RyOoXvV6ZsWoiVm

production:
    PARSE_APP_ID: KRsv5fl3h1k1qvRvhEQyITCnvIZ7eq8uJDJp9JRC
    PARSE_REST_KEY: SrQRoGsr3Hse9VTXaFnOA6CsopZxx8UjIvlMIFNJ